baseURL = 'https://fuentedederechocomar.github.io/template/'
languageCode = 'es-ar'
title = 'inicio'

[menu]
  [[menu.main]]
    pageRef = "search"
    weight = -100
    [menu.main.params]
      type = "search"
  [[menu.main]]
    identifier = "Ley"
    name = "Ley"
    url = "/ley/"
    weight = 1
  [[menu.main]]
    identifier = "Jurisprudencia"
    name = "Jurisprudencia"
    url = "/jurisprudencia/"
    weight = 2
  [[menu.main]]
    identifier = "Doctrina"
    name = "Doctrina"
    url = "/doctrina/"
    weight = 3
  [[menu.main]]
    identifier = "Novedades"
    name = "Novedades"
    url = "/novedades/"
    weight = 4
  [[menu.main]]
    identifier = "Etiquetas"
    name = "Etiquetas"
    pageRef = "tags"
    weight = 5

[params]
  description = "Fuente De Derecho"
  pwa = false # Agrego para testear evitar mensaje emergente 27/8/2025

  [params.search]
    enable = true

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"

[module]
  [[module.imports]]
    path = "github.com/imfing/hextra" 
