baseURL = 'https://fuentedederechocomar.github.io/templatenew/'
languageCode = 'es-ar'
title = 'inicio'

[menu]
 [[menu.main]]
    identifier = "Ley"
    name = "Ley"
    url = "/ley/"
    weight = 1
  [[menu.main]]
    identifier = "Jurisprudencia"
    name = "Jurisprudencia"
    url = "/jurisprudencia/"
    weight = 2
  [[menu.main]]
    identifier = "Doctrina"
    name = "Doctrina"
    url = "/doctrina/"
    weight = 3
  [[menu.main]]
    pageRef = "search"
    weight = -100
    [menu.main.params]
      type = "search"
 
  [[menu.main]]
    identifier = "Novedades"
    name = "Novedades"
    url = "/novedades/"
    weight = 4
  [[menu.main]]
   identifier = "Categorias"
   name = "Categor√≠as"
   pageRef = "categories"
   weight = 5  
  [[menu.main]]
    identifier = "Etiquetas"
    name = "Voces"    # Antes era name = "Etiquetas"
    pageRef = "tags"
    weight = 6

[params]
  description = "Fuente De Derecho"
  pwa = false # Agrego para testear evitar mensaje emergente 27/8/2025

  [params.search]
    enable = true

[taxonomies]
  category = "categories"
  categorias = "categories"
  categoria = "categories"
  tag = "tags"
  eqiqueta = "tags"
  author = "authors"
  voces = "voces" # Agrego 11/9/2025

[module]
  [[module.imports]]
    path = "github.com/imfing/hextra" 
